import Head from 'next/head'
import React from 'react'
import Navbar from '@/components/organisms/Header'
import Hero from '@/components/organisms/Hero'
import Tentang from '@/components/organisms/Tentang'
import ListMakanan from '@/components/organisms/ListMakan'
import Footer from '@/components/organisms/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Yuk Makan | Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <Tentang />
      <ListMakanan />
      <Footer />
    </>
  )
}
