import Head from 'next/head'
import React from 'react'


export default function Home ()  {

  return (
    <>
      <Head>
        <title>HARD SKILL TEST</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=''>
        <h1 className='text-2xl'>Activity List</h1>
      </main>
    </>
  )
}
